### ISSUE TITLE
[feat] Create portalbridge.com/cosmos to support cosmos chains

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#334]
**Task**
Create new portal bridge page for connect via gateway for cosmos chain. 

**Requirements**
- replicate this page in look and feel: https://www.portalbridge.com/sui/
- path is https://www.portalbridge.com/cosmos
- Add the connect widget and filter the options so that only Osmosis appears as the destination (also by default) (other cosmos chains to come in the future when supported)
launch date for the new site: dependent on connect + gateway release

**Comment by SamantaCasal** [comment]
✅ replicate this page in look and feel: https://www.portalbridge.com/sui/
✅ path is https://www.portalbridge.com/cosmos
❗ Add the connect widget and filter the options so that only Osmosis appears as the destination: This is not happening, currently all chains are visible and available to be selected.
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/70a55881-2399-4edf-9c2d-b9427e9057a6
FYI: @sebastianscatularo @mliu-xlabs

**Comment by sebastianscatularo** [comment]
@M-Picco is it possible to limit the target chain to only osmosis?

**Comment by M-Picco** [comment]
@SamantaCasal That error is expected and should be silenced in the latest version. Since the source is Goerli it won't get a vaa from the polling until the consistency level is reached, which may take around 15 minutes. We're looking into changing it to give a better feedback to the user.
