### ISSUE TITLE
[support] Ticket #9292

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Polygon
- Source Chain Wallet:
- Target Chain: Solana
- Target Chain Wallet:
- Asset Type: tBTC
- Tx: 0x02d1ad0c4bf987963835411929dc8b55ff32ef8f1c4120ab558302c21d90a73a
```

### Anything else?

User: I am Alistair from carrier bridge. I have a user who actually did the above bridge but because the code wasn't updated from carrier end so there a VAA created in wormhole. 

Could you check if the funds could be Refunded and I will get user to bridge again as we have updated the new native TBTC gateway on Solana. 

Thank you.

**Comment by sebastianscatularo** [comment]
The user should be able to bridge it back using portalbridge.com and get the origin asset, then the user should be able to bridge again through the proper tBTC flow. 

Due to the VAA is not yet redeemed, the user needs to redeem it first, and then bridge it back to the origin address (polygon seems to be)

- https://www.portalbridge.com/#/redeem?sourceChain=polygon&transactionId=0x02d1ad0c4bf987963835411929dc8b55ff32ef8f1c4120ab558302c21d90a73a

**Comment by dry2022** [comment]
ok thanks!

**Comment by Dahtank** [comment]
Closing

Reason: This ticket is the same issue as https://github.com/XLabs/portal-bridge-ui/issues/399 and https://github.com/XLabs/portal-bridge-ui/issues/325
