### ISSUE TITLE
[support] Cannot redeem the token to the target chain（Ticket #9142)

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:OPTIMISM
- Source Chain Wallet:0xaf4ed88badbfd847c6d43a23e58277f212c46132
- Target Chain:SOLANA
- Target Chain Wallet:FwCc9ehpx4U7jdTnX9hnmmkqRVsRLLPyzHZf8s3tRTCR
- Asset Type:Token
- Tx:https://optimistic.etherscan.io/tx/0x5fb4a0f0c591a6b4dc6ca2aae771e3162e194bfbb67091af59c75db6140e69f7
```

### Current Behavior

Information: Cannot redeem the token to the target chain
Error message: Unexpected error

### Steps To Reproduce

redeem workflow

### Anything else?

![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/dcf27e35-3d24-4da4-b076-7a996f8120a4)

**Comment by Dahtank** [comment]
This ticket is the same issue as #393 and #325

**Comment by willis20188** [comment]
Any updates so far?

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you try to reproduce it, once you get some spare time :)

**Comment by SamantaCasal** [comment]
FYI: @sebastianscatularo @willis20188 
This issue seems to be the same issue that is in [#325](https://github.com/XLabs/portal-bridge-ui/issues/325). We are (@yuli-ferna ) working to fix it.  So, I changed the status IN PROGRESS. 
Evidence: 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/300bdcb2-bcc0-4a28-b264-df9a4df85a2b

**Comment by drisAloma** [comment]
Hello, 
This has been resolved, thank you!
